[package]
name = "rust-raytracer"
version = "0.1.0"
authors = ["Mèir Noordermeer <meirnoordermeer@me.com>"]
edition = "2018"

[profile.release]
debug = true

# Non-release compilation profile for any non-workspace member.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bvh = { path = "bvh" }
scene = { path = "scene" }
fb-template = { path = "fb-template" }
rayon = "1.3.0"
num_cpus = "1.12.0"
glam = "0.8.6"
rand = "0.7.3"
tobj = "1.0.0"
num = "0.2.1"
crossbeam = "0.7.3"
wgpu = "0.5.0"
futures = "0.3.4"